### ISSUE TITLE
The assembly is unsigned

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus.StructureMap#44]
The released package of NServiceBus.StructureMap is unsigned, why?
Can you explain the reasoning?

This came up from a user question in support. 

cc / @Particular/container-maintainers

**Comment by WilliamBZA** [comment]
It appears it was removed 3 years ago for some reason https://github.com/Particular/NServiceBus.StructureMap/commit/5efbf5739c1964a4159ae1f0f2fd6120f941860d

Probably an oversight that it wasn't re-added at some point

**Comment by SimonCropp** [comment]
SM is not signed so we cant

**Comment by mauroservienti** [comment]
@indualagarsamy which version of SM are they using and which version of our package?

**Comment by indualagarsamy** [comment]
@mauroservienti - They are using NServiceBus version 5.2.8 and would like to use https://www.nuget.org/packages/structuremap/3.1.6.186

**Comment by indualagarsamy** [comment]
As, @SimonCropp pointed out, and also based on this comment from Jeremy Miller, https://github.com/structuremap/structuremap/issues/450#issuecomment-189031868, I am closing this issue, because if StructureMap isn't signing their assembly, should we?
