### ISSUE TITLE
Child containers cannot be supported

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.StructureMap#52]
A customer raised an issue in the core when attempting to use a child container with FileBasedDataBus:

```csharp
endpointConfiguration.UseDataBus<FileShareDataBus>().BasePath(@"c:\temp\");
var container = new Container().CreateChildContainer();
endpointConfiguration.UseContainer<StructureMapBuilder>(c => c.ExistingContainer(container));
```

This results in a `NullReferenceException` when starting the DataBus, as the [`IDataBus` property in `DataBus`](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/DataBus/DataBus.cs#L50) is not injected by StructureMap in this use case.

Policies are [used to configure setter injection in StructureMap](https://github.com/Particular/NServiceBus.StructureMap/blob/develop/src/NServiceBus.StructureMap/ConfigurationExpressionExtensions.cs#L11).

Applying policies to child containers is [not a supported use case](https://github.com/structuremap/structuremap/issues/596#issuecomment-317722797) by StructureMap. 

Raise via https://github.com/Particular/NServiceBus/issues/4968

**Comment by boblangley** [comment]
I propose we check for child containers when a container is passed in a throw an exception to prevent this from tripping up users in the future.

**Comment by timbussmann** [comment]
given that we removed the property injection for the databus in core with v7, I think we can close this? Thoughts @boblangley ?

**Comment by boblangley** [comment]
The databus property injection was the symptom. Are all setter injections removed? How do we know the customer isn't use it? I still think rejecting child containers, or at least providing a warning, may be a safer choice.

**Comment by timbussmann** [comment]
@boblangley according to https://github.com/Particular/NServiceBus/issues/4968#issuecomment-332473258 I've tested that more than 2 years ago. I'd say this issue is fixed and would suggest raising a new issue if there is another problem with property injection somewhere.

**Comment by mikeminutillo** [comment]
@boblangley if this is still relevant, please reopen it.
