### ISSUE TITLE
NServiceBus.StructureMap v5.1.0 not compatible with StructureMap < 4

### ISSUE THREAD

**Issue by janv8000** [Particular/NServiceBus.StructureMap#58]
When starting my endpoint (hosted with NServiceBus.Host) I get an exception with the following message:
> System.TypeLoadException: 'Could not load type 'StructureMap.Registry' from assembly 'StructureMap, Version=3.1.9.463, Culture=neutral, PublicKeyToken=null'.'

v5.1.0 nuspec claims compatibility with the following combination:
NServiceBus (>= 5.0.0 && < 6.0.0)
StructureMap (>= 3.0.5.130 && < 5.0.0)

Currently my application has the following combinations in packages.config:

    <package id="NServiceBus" version="5.2.25" targetFramework="net461" />
    <package id="NServiceBus.Host" version="5.0.11" targetFramework="net461" />
    ... 
    <package id="NServiceBus.StructureMap" version="5.1.0" targetFramework="net461" />
    <package id="structuremap" version="3.1.9.463" targetFramework="net461" />

However the `Registry` type was moved to the root namespace in SM4, see https://github.com/structuremap/structuremap/issues/405 and https://github.com/structuremap/structuremap/commit/785bcd9855194ad7bd29aa8964482bbe51d84912#diff-5b505a9d5295e52a90dccc610f050239

So I believe the package dependencies should be changed to require at least SM4?

**Comment by WilliamBZA** [comment]
Good catch @janv8000. I'll push a version with updated range out

**Comment by timbussmann** [comment]
closing this as this seems to be very old and addressed by newer packages. Looking at the releases, I can't see 5.1.1 being released though, so the resolution is to update to newer, supported versions of the package.
